services:
  web:
    restart: always
    build: ./mlflow
    image: mlflow_server
    container_name: mlflow_server
    ports:
      - "${MLFLOW_PORT:-5000}:5000"
    volumes:
      - "${MLFLOW_TRACKING_DIRECTORY:-mlruns}:/mlruns"
    command: >
      mlflow server
        --backend-store-uri mlruns/tracking
        --default-artifact-root mlruns/artifacts
        --host 0.0.0.0